services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-todo-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tododb
      - SPRING_DATASOURCE_USERNAME=todo_user
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - todo-network

  db:
    image: postgres:15
    container_name: my-todo-db
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  db_data:

networks:
  todo-network:
